apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-api
  namespace: telemetry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-api
  template:
    metadata:
      labels:
        app: telemetry-api
    spec:
      serviceAccountName: telemetry-sa
      containers:
      - name: api
        image: 045064752559.dkr.ecr.ap-south-1.amazonaws.com/telemetry-api:09e8c4683092abb44592f6dcf821c326720e896e
        env:
          - name: SQS_QUEUE_URL
            value: "https://sqs.ap-south-1.amazonaws.com/045064752559/telemetry-events-queue"
        ports:
          - containerPort: 5678
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 5
          periodSeconds: 10