autoDiscovery:
  clusterName: dev-eks-cluster
awsRegion: ap-south-1
rbac:
  create: true
serviceAccount:
  create: true
  name: cluster-autoscaler
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::<ACCOUNT_ID>:role/cluster-autoscaler-role"
extraArgs:
  balance-similar-node-groups: true
  skip-nodes-with-system-pods: false
